import React, { useContext } from "react";
import { DadosEconomyGlobalContext } from "../dadosEconomyGlobal";
/* =====================================================
   📦 CATÁLOGO DE PRODUTOS (fonte única da verdade)
===================================================== */

export const productsCatalog = {
  // 🌱 AGRICULTURA
  sementeMilho: {
    id: "sementeMilho",
    nome: "Semente De Milho",
    icon: "🌱",
    unidade: "sacas",
    setor: "agricultura",
    categoriaFisica: "agrícolas secos",
    slotSize: 0.5,
  },
  sementeSoja: {
    id: "sementeSoja",
    nome: "Semente De Soja",
    icon: "🌱",
    unidade: "sacas",
    setor: "agricultura",
    categoriaFisica: "agrícolas secos",
    slotSize: 0.5,
  },
  sementeTrigo: {
    id: "sementeTrigo",
    nome: "Semente De Trigo",
    icon: "🌱",
    unidade: "sacas",
    setor: "agricultura",
    categoriaFisica: "agrícolas secos",
    slotSize: 0.5,
  },
  sementeAlgodão: {
    id: "sementeAlgodão",
    nome: "Semente De Algodão",
    icon: "🌱",
    unidade: "sacas",
    setor: "agricultura",
    categoriaFisica: "agrícolas secos",
    slotSize: 0.5,
  },
  milho: {
    id: "milho",
    nome: "Milho",
    icon: "🌽",
    unidade: "sacas",
    setor: "agricultura",
    categoriaFisica: "agrícolas secos",
    slotSize: 0.5,
  },
  soja: {
    id: "soja",
    nome: "Soja",
    icon: "🫘",
    unidade: "sacas",
    setor: "agricultura",
    categoriaFisica: "agrícolas secos",
    slotSize: 0.5,
  },
  trigo: {
    id: "trigo",
    nome: "Trigo",
    icon: "🌾",
    unidade: "sacas",
    setor: "agricultura",
    categoriaFisica: "agrícolas secos",
    slotSize: 0.5,
  },
  algodão: {
    id: "algodão",
    nome: "Algodão",
    icon: "☁️",
    unidade: "sacas",
    setor: "agricultura",
    categoriaFisica: "agrícolas secos",
    slotSize: 0.5,
  },

  ervaAnalgésica: {
    id: "ervaAnalgésica",
    nome: "Erva Analgésica",
    icon: "🌿",
    unidade: "sacas",
    setor: "agricultura",
    categoriaFisica: "agrícolas secos",
    slotSize: 0.5,
  },

  plantaAntissépticas: {
    id: "plantaAntissépticas",
    nome: "Plantas Antissépticas",
    icon: "🌱",
    unidade: "sacas",
    setor: "agricultura",
    categoriaFisica: "agrícolas secos",
    slotSize: 0.5,
  },




  vaca: {
    id: "vaca",
    nome: "Vaca",
    icon: "🐮",
    unidade: "unidade",
    setor: "agricultura",
    categoriaFisica: "animais",
    slotSize: 3,
  },

  galinha: {
    id: "galinha",
    nome: "Galinha",
    icon: "🐔",
    unidade: "unidade",
    setor: "agricultura",
    categoriaFisica: "animais",
    slotSize: 0.2,
  },

  ovelha: {
    id: "ovelha",
    nome: "Ovelha",
    icon: "🐑",
    unidade: "unidade",
    setor: "agricultura",
    categoriaFisica: "animais",
    slotSize: 1,
  },

  porco: {
    id: "porco",
    nome: "Porco",
    icon: "🐷",
    unidade: "unidade",
    setor: "agricultura",
    categoriaFisica: "animais",
    slotSize: 1.5,
  },

  couro: {
    id: "couro",
    nome: "Couro",
    icon: "🟫",
    unidade: "kg",
    setor: "agricultura",
    categoriaFisica: "biomassa / orgânicos",
    slotSize: 0.2,
  },

  couroPremium: {
    id: "couroPremium",
    nome: "Couro Premium",
    icon: "👜",
    unidade: "kg",
    setor: "agricultura",
    categoriaFisica: "produtos manufaturados",
    slotSize: 20,
  },

  lã: {
    id: "lã",
    nome: "Lã",
    icon: "🧶",
    unidade: "kg",
    setor: "agricultura",
    categoriaFisica: "produtos manufaturados",
    slotSize: 5,
  },


  arvoreEucalipto: {
    id: "arvoreEucalipto",
    nome: "Arvore De Eucalipto",
    icon: "🌳",
    unidade: "arvore",
    setor: "agricultura",
    categoriaFisica: "biomassa / orgânicos",
    slotSize: 5,
  },

  arvoreNativa: {
    id: "arvoreNativa",
    nome: "Arvore Nativa",
    icon: "🌳",
    unidade: "arvore",
    setor: "agricultura",
    categoriaFisica: "biomassa / orgânicos",
    slotSize: 5,
  },

  toraEucalipto: {
    id: "toraEucalipto",
    nome: "Toras De Eucalipto",
    icon: "🪵",
    unidade: "unidade",
    setor: "agricultura",
    categoriaFisica: "biomassa / orgânicos",
    slotSize: 5,
  },

  toraNativa: {
    id: "toraNativa",
    nome: "Tora Nativa",
    icon: "🪵",
    unidade: "unidade",
    setor: "agricultura",
    categoriaFisica: "biomassa / orgânicos",
    slotSize: 5,
  },

  sodaCáustica: {
    id: "sodaCáustica",
    nome: "Soda Caústica",
    icon: "🧪",
    unidade: "kg",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 5,
  },

  ácidoSulfúrico: {
    id: "ácidoSulfúrico",
    nome: "Ácido Sulfúrico",
    icon: "⚠️",
    unidade: "kg",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 5,
  },

  sal: {
    id: "sal",
    nome: "Sal",
    icon: "🧂",
    unidade: "kg",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 5,
  },

  benzeno: {
    id: "benzeno",
    nome: "Benzeno",
    icon: "🧪",
    unidade: "litro",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 5,
  },

  enxofreBruto: {
    id: "enxofreBruto",
    nome: "Enxofre Bruto",
    icon: "🟡",
    unidade: "litro",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 5,
  },

  cloro: {
    id: "cloro",
    nome: "Cloro",
    icon: "🧪",
    unidade: "kg",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 5,
  },

  pigmento: {
    id: "pigmento",
    nome: "Pigmento",
    icon: "🎨",
    unidade: "litro",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 5,
  },

  cavacoMadeiraNativa: {
    id: "cavacoMadeiraNativa",
    nome: "Cavaco De Madeira",
    icon: "🪵",
    unidade: "kg",
    setor: "agricultura",
    categoriaFisica: "biomassa / orgânicos",
    slotSize: 5,
  },

  cavacoEucalipto: {
    id: "cavacoEucalipto",
    nome: "Cavaco De Eucalipto",
    icon: "🪵",
    unidade: "kg",
    setor: "agricultura",
    categoriaFisica: "biomassa / orgânicos",
    slotSize: 5,
  },

  fardoCelulose: {
    id: "fardoCelulose",
    nome: "Fardo De Celulose",
    icon: "📦",
    unidade: "fardo",
    setor: "industria",
    categoriaFisica: "biomassa / orgânicos",
    slotSize: 5,
  },
  bobinaKraft: {
    id: "bobinaKraft",
    nome: "Bobina De Papel Kraft",
    icon: "🪵",
    unidade: "bobina",
    setor: "industria",
    categoriaFisica: "produtos manufaturados",
    slotSize: 5,
  },
  bobinaBranco: {
    id: "bobinaBranco",
    nome: "Bobina De Papel Branco",
    icon: "🧻",
    unidade: "bobina",
    setor: "industria",
    categoriaFisica: "produtos manufaturados",
    slotSize: 5,
  },

  tintaIndustrial: {
    id: "tintaIndustrial",
    nome: "Tinta Industrial",
    icon: "🎨",
    unidade: "Litro",
    setor: "industria",
    categoriaFisica: "produtos manufaturados",
    slotSize: 5,
  },

  livroComum: {
    id: "livroComum",
    nome: "Livro Comum",
    icon: "📕",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "produtos manufaturados",
    slotSize: 5,
  },
  livroPremium: {
    id: "livroPremium",
    nome: "Livro Premium",
    icon: "📙",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "produtos manufaturados",
    slotSize: 5,
  },

  fioAlgodão: {
    id: "fioAlgodão",
    nome: "Fio De Algodão",
    icon: "🧵",
    unidade: "rolo",
    setor: "industria",
    categoriaFisica: "produtos manufaturados",
    slotSize: 5,
  },

  fioLã: {
    id: "fioLã",
    nome: "Fio De Lã",
    icon: "🧶",
    unidade: "rolo",
    setor: "industria",
    categoriaFisica: "produtos manufaturados",
    slotSize: 5,
  },

  fioIndustrial: {
    id: "fioIndustrial",
    nome: "Fio Industrial",
    icon: "🪢",
    unidade: "rolo",
    setor: "industria",
    categoriaFisica: "produtos manufaturados",
    slotSize: 5,
  },

  colaIndustrial: {
    id: "colaIndustrial",
    nome: "Cola",
    icon: "🧴",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 5,
  },

  petróleoBruto: {
    id: "petróleoBruto",
    nome: "Petróleo Bruto",
    icon: "🛢️",
    unidade: "litro",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 5,
  },

  diesel: {
    id: "diesel",
    nome: "Diesel",
    icon: "⛽",
    unidade: "litro",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 5,
  },

  solvente: {
    id: "solvente",
    nome: "Solvente",
    icon: "🛢️",
    unidade: "litro",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 5,
  },

  nafta: {
    id: "nafta",
    nome: "Nafta",
    icon: "🛢️",
    unidade: "litro",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 5,
  },

  caixaPapelão: {
    id: "caixaPapelão",
    nome: "Caixa Papelão",
    icon: "📦",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "produtos manufaturados",
    slotSize: 5,
  },

  caixaPequenaPapelão: {
    id: "caixaPequenaPapelão",
    nome: "Caixa Pequena Papelão",
    icon: "📦",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "produtos manufaturados",
    slotSize: 5,
  },

  sacolaPapelão: {
    id: "sacolaPapelão",
    nome: "Sacola De Papelão",
    icon: "🛍️",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "produtos manufaturados",
    slotSize: 5,
  },

  sacasIndustriais: {
    id: "sacasIndustriais",
    nome: "Sacas Industriais",
    icon: "📦",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "produtos manufaturados",
    slotSize: 5,
  },

  tecidoTecnico: {
    id: "tecidoTecnico",
    nome: "Tecido Tecnico(Dry-FIT)",
    icon: "👕",
    unidade: "rolo",
    setor: "industria",
    categoriaFisica: "produtos manufaturados",
    slotSize: 5,
  },

  aditivoDeNylon: {
    id: "aditivoDeNylon",
    nome: "Aditivo De Nylon",
    icon: "⚗️",
    unidade: "rolo",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 5,
  },

  saisDeCromo: {
    id: "saisDeCromo",
    nome: "Sais De Cromo",
    icon: "🧪",
    unidade: "kg",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 5,
  },

  polímero: {
    id: "polímero",
    nome: "Polímero",
    icon: "⚗️",
    unidade: "litro",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 5,
  },

  vidroTécnico: {
    id: "vidroTécnico",
    nome: "Vidro Técnico",
    icon: "🧪",
    unidade: "kg",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 5,
  },

  pvcIndustrial: {
    id: "pvcIndustrial",
    nome: "PVC Industrial",
    icon: "⚗️",
    unidade: "litro",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 5,
  },

  resinaEmbalagem: {
    id: "resinaEmbalagem",
    nome: "Resina De Embalagem",
    icon: "🧪",
    unidade: "litro",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 5,
  },


  termoplásticoRígido: {
    id: "termoplásticoRígido",
    nome: "Termoplástico Rígido",
    icon: "🧪",
    unidade: "kg",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 5,
  },

  plásticoIsolante: {
    id: "plásticoIsolante",
    nome: "Plástico Isolante",
    icon: "🧪",
    unidade: "kg",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 5,
  },


  oleoAntimicrobiano: {
    id: "oleoAntimicrobiano",
    nome: "Óleo Antimicrobiano",
    icon: "💊",
    unidade: "litro",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 0.5,
  },
  óleoIndustrial: {
    id: "óleoIndustrial",
    nome: "Óleo Industrial",
    icon: "💧",
    unidade: "litro",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 0.5,
  },

  extratoAlívio: {
    id: "extratoAlívio",
    nome: "Extrato De Alívio",
    icon: "💊",
    unidade: "litro",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 0.5,
  },

  pASintético: {
    id: "pASintético",
    nome: "P.A Sintético",
    icon: "🧪",
    unidade: "litro",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 0.5,
  },

  resinaIndustrial: {
    id: "resinaIndustrial",
    nome: "Resina Industrial",
    icon: "🧴",
    unidade: "litro",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 0.5,
  },

  excipienteFarmacêutico: {
    id: "excipienteFarmacêutico",
    nome: "Excipiente Farmacêutico",
    icon: "💊",
    unidade: "litro",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 0.5,
  },

  comprimidosGenéricos: {
    id: "comprimidosGenéricos",
    nome: "Comprimidos Genéricos",
    icon: "💊",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 0.5,
  },

  frascoVitamina: {
    id: "frascoVitamina",
    nome: "Frasco De Vitamina",
    icon: "💊",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 0.5,
  },

  bisnagaTratamento: {
    id: "bisnagaTratamento",
    nome: "Bisnaga De Tratamento",
    icon: "🧴",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 0.5,
  },

  testeLaboratorial: {
    id: "testeLaboratorial",
    nome: "Teste Laboratorial",
    icon: "🔬",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 0.5,
  },

  enzimaIndustrial: {
    id: "enzimaIndustrial",
    nome: "Enzima Industrial",
    icon: "🧬",
    unidade: "kg",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 0.5,
  },

  polímeroReforçado: {
    id: "polímeroReforçado",
    nome: "Polímero Reforçado",
    icon: "💊",
    unidade: "kg",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 0.5,
  },


  camisetaAlgodão: {
    id: "camisetaAlgodão",
    nome: "Camiseta De Algodão",
    icon: "👕",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "produtos manufaturados",
    slotSize: 5,
  },

  casacoLã: {
    id: "casacoLã",
    nome: "casaco De Lã",
    icon: "🧥",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "produtos manufaturados",
    slotSize: 5,
  },

  roupasDryFit: {
    id: "roupasDryFit",
    nome: "Roupa DryFit",
    icon: "🎽",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "produtos manufaturados",
    slotSize: 5,
  },



  tenisCorrida: {
    id: "tenisCorrida",
    nome: "Tênis De Corrida",
    icon: "👟",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "produtos manufaturados",
    slotSize: 5,
  },

  sapatoLuxo: {
    id: "sapatoLuxo",
    nome: "Sapato de Luxo",
    icon: "👞",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "produtos manufaturados",
    slotSize: 5,
  },

  biomassaLíquida: {
    id: "biomassaLíquida",
    nome: "Biomassa Líquida",
    icon: "🧪",
    unidade: "litro",
    setor: "industria",
    categoriaFisica: "fluidos",
    slotSize: 5,
  },

  serragem: {
    id: "serragem",
    nome: "Serragem",
    icon: "🍂",
    unidade: "kg",
    setor: "agricultura",
    categoriaFisica: "biomassa / orgânicos",
    slotSize: 5,
  },

  esterco: {
    id: "esterco",
    nome: "Esterco",
    icon: "💩",
    unidade: "sacas",
    setor: "agricultura",
    categoriaFisica: "biomassa / orgânicos",
    slotSize: 0.1,
  },


  racaoDeVacas: {
    id: "racaoDeVacas",
    nome: "Ração De Vacas",
    icon: "🥡",
    unidade: "sacas",
    setor: "industria",
    categoriaFisica: "biomassa / orgânicos",
    slotSize: 0.1,
  },

  racaoDeAves: {
    id: "racaoDeAves",
    nome: "Ração De Aves",
    icon: "🥡",
    unidade: "sacas",
    setor: "industria",
    categoriaFisica: "biomassa / orgânicos",
    slotSize: 0.1,
  },

  racaoDeOvinos: {
    id: "racaoDeOvinos",
    nome: "Ração De Ovinos",
    icon: "🥡",
    unidade: "sacas",
    setor: "industria",
    categoriaFisica: "biomassa / orgânicos",
    slotSize: 0.1,
  },

  racaoDePorco: {
    id: "racaoDePorco",
    nome: "Ração De Porco",
    icon: "🥡",
    unidade: "sacas",
    setor: "industria",
    categoriaFisica: "biomassa / orgânicos",
    slotSize: 0.1,
  },

  fertilizantePlantação: {
    id: "fertilizantePlantação",
    nome: "Fertilizante De Plantações",
    icon: "♻️",
    unidade: "saco",
    setor: "industria",
    categoriaFisica: "biomassa / orgânicos",
    slotSize: 1,
  },

  fertilizanteFlorestal: {
    id: "fertilizanteFlorestal",
    nome: "Fertilizante De Florestal",
    icon: "♻️",
    unidade: "saco",
    setor: "industria",
    categoriaFisica: "biomassa / orgânicos",
    slotSize: 1,
  },





  // 🥩 COMÉRCIO
  carneBovina: {
    id: "carneBovina",
    nome: "Carne Bovina",
    icon: "🥩",
    unidade: "kg",
    setor: "comercio",
    categoriaFisica: "perecíveis",
    slotSize: 0.1,
  },
  frango: {
    id: "frango",
    nome: "Frango",
    icon: "🍗",
    unidade: "kg",
    setor: "comercio",
    categoriaFisica: "perecíveis",
    slotSize: 0.4,
  },
  carneSuina: {
    id: "carneSuina",
    nome: "Carne Suína",
    icon: "🥓",
    unidade: "kg",
    setor: "comercio",
    categoriaFisica: "perecíveis",
    slotSize: 0.45,
  },
  carneOvino: {
    id: "carneOvino",
    nome: "Carne De Ovino",
    icon: "🍖",
    unidade: "kg",
    setor: "comercio",
    categoriaFisica: "perecíveis",
    slotSize: 0.3,
  },


  // 🏭 INDÚSTRIA
  carroPopular: {
    id: "carroPopular",
    nome: "Carro Popular",
    icon: "🚗",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "veículos",
    slotSize: 6,
  },
  carroEsportivo: {
    id: "carroEsportivo",
    nome: "Carro Esportivo",
    icon: "🏎️",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "veículos",
    slotSize: 6,
  },
  carroElétrico: {
    id: "carroElétrico",
    nome: "Carro Elétrico",
    icon: "🚙",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "veículos",
    slotSize: 6,
  },
  hiperCarroElétrico: {
    id: "hiperCarroElétrico",
    nome: "Hiper Carro Elétrico",
    icon: "🏎️",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "veículos",
    slotSize: 6,
  },
  caminhãoElétrico: {
    id: "caminhãoElétrico",
    nome: "Caminhão Elétrico",
    icon: "🚙",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "veículos",
    slotSize: 6,
  },
  escavadeira: {
    id: "escavadeira",
    nome: "Escavadeira",
    icon: "🚜",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "veículos",
    slotSize: 6,
  },
  suv: {
    id: "suv",
    nome: "SUV",
    icon: "🚙",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "veículos",
    slotSize: 6,
  },
  van: {
    id: "van",
    nome: "Van",
    icon: "🚐",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "veículos",
    slotSize: 8,
  },


  // ⛏️ MINÉRIOS
  minérioFerro: {
    id: "minérioFerro",
    nome: "Minério De Ferro",
    icon: "🪨",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },
  minérioDeCobre: {
    id: "minérioDeCobre",
    nome: "Minério De Cobre",
    icon: "🪨",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },
  minérioDeChumbo: {
    id: "minérioDeChumbo",
    nome: "Minério De Chumbo",
    icon: "🪨",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },
  lingoteChumbo: {
    id: "lingoteChumbo",
    nome: "Lingote De Chumbo",
    icon: "🧱",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },
  lingoteDeCobre: {
    id: "lingoteDeCobre",
    nome: "Lingote De Cobre",
    icon: "🧱",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },

  minérioDeEstanho: {
    id: "minérioDeEstanho",
    nome: "Minério De Estanho",
    icon: "🪨",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },
  minérioDeZinco: {
    id: "minérioDeZinco",
    nome: "Minério De Zinco",
    icon: "🪨",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },
  minérioDeGalho: {
    id: "minérioDeGalho",
    nome: "Minério De Galho",
    icon: "🪨",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },
  minérioDeIndio: {
    id: "minérioDeIndio",
    nome: "Minério De Índio",
    icon: "⛏️",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },
  minérioDeNiquel: {
    id: "minérioDeNiquel",
    nome: "Minério De Níquel",
    icon: "⛏️",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },
  minérioDeCobalto: {
    id: "minérioDeCobalto",
    nome: "Minério De Cobalto",
    icon: "⛏️",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },
  minérioDeQuartzo: {
    id: "minérioDeQuartzo",
    nome: "Minério De Quartzo",
    icon: "💎",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },
  minérioDePrata: {
    id: "minérioDePrata",
    nome: "Minério De Prata",
    icon: "⚪",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },
  minérioDeOuro: {
    id: "minérioDeOuro",
    nome: "Minério De Ouro",
    icon: "🪙",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },

  minérioDeLítio: {
    id: "minérioDeLítio",
    nome: "Minério De Lítio",
    icon: "🪨",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },
  lítioPuro: {
    id: "lítioPuro",
    nome: "Lítio Puro",
    icon: "🔋",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },
  nanotuboCarbono: {
    id: "nanotuboCarbono",
    nome: "Nanotubo Carbono",
    icon: "📡",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  sondaTerreno: {
    id: "sondaTerreno",
    nome: "Sonda De Terreno",
    icon: "📡",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes eletrônicos",
    slotSize: 6,
  },
  scannerMédico: {
    id: "scannerMédico",
    nome: "Scanner Médico",
    icon: "📡",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes eletrônicos",
    slotSize: 6,
  },

  chipIA: {
    id: "chipIA",
    nome: "Chip de IA",
    icon: "🧠",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes eletrônicos",
    slotSize: 6,
  },

  chipWearables: {
    id: "chipWearables",
    nome: "Chip De Wearables",
    icon: "📟",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes eletrônicos",
    slotSize: 6,
  },

  computadorVoo: {
    id: "computadorVoo",
    nome: "Computador De Voo",
    icon: "✈️",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes eletrônicos",
    slotSize: 6,
  },

  processadorBlindado: {
    id: "processadorBlindado",
    nome: "Processador Blindado",
    icon: "🛡️",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes eletrônicos",
    slotSize: 6,
  },

  processadorSísmico: {
    id: "processadorSísmico",
    nome: "Processador Sísmico",
    icon: "🌋",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes eletrônicos",
    slotSize: 6,
  },

  sistemaGuia: {
    id: "sistemaGuia",
    nome: "Sistema De Guia",
    icon: "🗺️",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes eletrônicos",
    slotSize: 6,
  },
  bioChip: {
    id: "bioChip",
    nome: "Bio-Chip",
    icon: "🧬",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes eletrônicos",
    slotSize: 6,
  },
  câmeraPrecisão: {
    id: "câmeraPrecisão",
    nome: "Câmera De Precisão",
    icon: "📡",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes eletrônicos",
    slotSize: 6,
  },
  //AQUI
  sensoresCampoRemoto: {
    id: "sensoresCampoRemoto",
    nome: "Sensores De Campo Remoto",
    icon: "📡",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes eletrônicos",
    slotSize: 6,
  },
  lentePrecisão: {
    id: "lentePrecisão",
    nome: "Lente De Precisão",
    icon: "🔍",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes eletrônicos",
    slotSize: 6,
  },
  unidadeComando: {
    id: "unidadeComando",
    nome: "Unidade De Comando",
    icon: "🎛️",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes eletrônicos",
    slotSize: 6,
  },
  chipMemória: {
    id: "chipMemória",
    nome: "Chip De Memória",
    icon: "🧠",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes eletrônicos",
    slotSize: 6,
  },
  controle: {
    id: "controle",
    nome: "Controle",
    icon: "🎮",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes eletrônicos",
    slotSize: 6,
  },
  painélDeControle: {
    id: "painélDeControle",
    nome: "Painél De Controle",
    icon: "🎛️",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes eletrônicos",
    slotSize: 6,
  },


  minérioDeManganês: {
    id: "minérioDeManganês",
    nome: "Minério De Manganês",
    icon: "⛏️",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },

  minérioDeCromo: {
    id: "minérioDeCromo",
    nome: "Minério De Cromo",
    icon: "⛏️",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },
  minérioNeodímio: {
    id: "minérioNeodímio",
    nome: "Minério De Neodímio",
    icon: "🧲",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },

  minérioDeTitânio: {
    id: "minérioDeTitânio",
    nome: "Minério De Titânio",
    icon: "⛏️",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },

  ligaDeBronze: {
    id: "ligaDeBronze",
    nome: "Liga De Bronze",
    icon: "🥉",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  ligaDeSolda: {
    id: "ligaDeSolda",
    nome: "Liga De Solda",
    icon: "🖇️",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },

  ligaDeLatão: {
    id: "ligaDeLatão",
    nome: "Liga De Latão",
    icon: "🟡",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  superligaTérmica: {
    id: "superligaTérmica",
    nome: "Superliga Térmica",
    icon: "🔥",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  ligaDeOuro: {
    id: "ligaDeOuro",
    nome: "Liga De Ouro",
    icon: "📀",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  compostoSemicondutor: {
    id: "compostoSemicondutor",
    nome: "Composto Semicondutor",
    icon: "⚫",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  celulaSolar: {
    id: "celulaSolar",
    nome: "Celula Solar",
    icon: "☀️",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  engrenagem: {
    id: "engrenagem",
    nome: "Engrenagem",
    icon: "⚙️",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  placaIndustrial: {
    id: "placaIndustrial",
    nome: "Placa Industrial",
    icon: "📟",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  robôServiço: {
    id: "robôServiço",
    nome: "Robô De Serviço",
    icon: "🤖",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  controladorLógico: {
    id: "controladorLógico",
    nome: "Controlador Lógico",
    icon: "🎛️",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes eletrônicos",
    slotSize: 6,
  },

  //AQUI
  ControladorCarga: {
    id: "ControladorCarga",
    nome: "Controlador De Carga",
    icon: "🎛️",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes eletrônicos",
    slotSize: 6,
  },
  placaGestãoEnergia: {
    id: "placaGestãoEnergia",
    nome: "Placa De Gestão De Energia",
    icon: "🟩",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes eletrônicos",
    slotSize: 6,
  },
  placaFrequência: {
    id: "placaFrequência",
    nome: "Placa De Frequência",
    icon: "🟩",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes eletrônicos",
    slotSize: 6,
  },
  processadorAltaPerformance: {
    id: "processadorAltaPerformance",
    nome: "Processador Alta Performance",
    icon: "⚫",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes eletrônicos",
    slotSize: 6,
  },
  bateriaPortátil: {
    id: "bateriaPortátil",
    nome: "Bateria Portátil",
    icon: "🔋",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes eletrônicos",
    slotSize: 6,
  },
  microControlador: {
    id: "microControlador",
    nome: "Micro Controlador",
    icon: "⚫",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes eletrônicos",
    slotSize: 6,
  },
  droneLogístico: {
    id: "droneLogístico",
    nome: "Drone Logístico",
    icon: "🛸",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  robôMineração: {
    id: "robôMineração",
    nome: "Robô De Mineração",
    icon: "🤖",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  palhetaPrecisão: {
    id: "palhetaPrecisão",
    nome: "Palheta De Precisão",
    icon: "⚫",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  rolamento: {
    id: "rolamento",
    nome: "Rolamento",
    icon: "⚙️",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  fioCobre: {
    id: "fioCobre",
    nome: "Fio De Cobre",
    icon: "🔌",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  microMotor: {
    id: "microMotor",
    nome: "Micro Motor",
    icon: "⚙️",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  motorCombustão: {
    id: "motorCombustão",
    nome: "Motor A Combustão",
    icon: "🚂",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  motorElétrico: {
    id: "motorElétrico",
    nome: "Motor Elétrico",
    icon: "🌀",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  motorAvião: {
    id: "motorAvião",
    nome: "Motor Avião",
    icon: "⚫",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  motorFoguete: {
    id: "motorFoguete",
    nome: "Motor Foguete",
    icon: "🚀",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  motorNaval: {
    id: "motorNaval",
    nome: "Motor Naval",
    icon: "🚢",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  motorMíssil: {
    id: "motorMíssil",
    nome: "Motor Míssil",
    icon: "💥",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  jatoComercial: {
    id: "jatoComercial",
    nome: "Jato Comercial",
    icon: "✈️",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "aeronaves",
    slotSize: 6,
  },
  aviãoCargueiro: {
    id: "aviãoCargueiro",
    nome: "Avião Cargueiro",
    icon: "✈️",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "aeronaves",
    slotSize: 6,
  },
  caçaDefesa: {
    id: "caçaDefesa",
    nome: "Caça De Defesa",
    icon: "✈️",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "aeronaves",
    slotSize: 6,
  },
  satéliteOrbital: {
    id: "satéliteOrbital",
    nome: "Satélite Orbital",
    icon: "🛰️",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "aeronaves",
    slotSize: 6,
  },

  sondaEspacial: {
    id: "sondaEspacial",
    nome: "Sonda Espacial",
    icon: "🛰️",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "aeronaves",
    slotSize: 6,
  },
  fogueteLançamento: {
    id: "fogueteLançamento",
    nome: "Foguete De Lançamento",
    icon: "🚀",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "aeronaves",
    slotSize: 6,
  },
  navioConteineres: {
    id: "navioConteineres",
    nome: "Navio De Conteineres",
    icon: "🚢",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "aeronaves",
    slotSize: 6,
  },
  navioPetroleiro: {
    id: "navioPetroleiro",
    nome: "Navio Petroleiro",
    icon: "🚢",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "aeronaves",
    slotSize: 6,
  },
  navioPesquisa: {
    id: "navioPesquisa",
    nome: "Navio Pesquisa",
    icon: "🚢",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "aeronaves",
    slotSize: 6,
  },
  unidadeCélula: {
    id: "unidadeCélula",
    nome: "Unidade De Célula",
    icon: "🔋",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  bateriaTracionamento: {
    id: "bateriaTracionamento",
    nome: "Bateria Tracionamento",
    icon: "🔋",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  armazenamentoFixo: {
    id: "armazenamentoFixo",
    nome: "Armazenamento Fixo",
    icon: "🔋",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  pistãoHidráulico: {
    id: "pistãoHidráulico",
    nome: "Pistão Hidráulico",
    icon: "🔩",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  braçoHidráulico: {
    id: "braçoHidráulico",
    nome: "Braço Hidráulico",
    icon: "🦾",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  TurbinaEstacionária: {
    id: "TurbinaEstacionária",
    nome: "Turbina Estacionária",
    icon: "🎡",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },

  blocoMagnético: {
    id: "blocoMagnético",
    nome: "Bloco Magnético",
    icon: "🧲",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  contatoDePrata: {
    id: "contatoDePrata",
    nome: "Contato De Prata",
    icon: "⚫",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  periférico: {
    id: "periférico",
    nome: "Periférico",
    icon: "⌨️",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },

  ferroGusa: {
    id: "ferroGusa",
    nome: "Ferro Gusa",
    icon: "🪨",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },

  lingoteAço: {
    id: "lingoteAço",
    nome: "Lingote Aço",
    icon: "🧱",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },

  chapaAço: {
    id: "chapaAço",
    nome: "Chapa De Aço",
    icon: "🗒️",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },

  chassiStandard: {
    id: "chassiStandard",
    nome: "Chassi Standard",
    icon: "🚜",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  chassiLuxo: {
    id: "chassiLuxo",
    nome: "Chassi Luxo",
    icon: "🏎️",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },

  vigaH: {
    id: "vigaH",
    nome: "Viga Em H",
    icon: "🏗️",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },

  chapaAlumínio: {
    id: "chapaAlumínio",
    nome: "Chapa De Alumínio",
    icon: "⬜",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },

  chapaAltaTensão: {
    id: "chapaAltaTensão",
    nome: "Chapa De Alta Tensão",
    icon: "🔘",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },

  placaReforçada: {
    id: "placaReforçada",
    nome: "Placa Reforçada",
    icon: "⬜",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  sistemaTransmissão: {
    id: "sistemaTransmissão",
    nome: "Sistema De Transmissão",
    icon: "⚙️",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  válvulaHidráulica: {
    id: "válvulaHidráulica",
    nome: "Válvula Hidráulica",
    icon: "🔧",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  redutorCarga: {
    id: "redutorCarga",
    nome: "Redutor De Carga",
    icon: "🎛️",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },

  lingoteTitânio: {
    id: "lingoteTitânio",
    nome: "lingote De Titânio",
    icon: "🧱",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },

  lingoteAlumínio: {
    id: "lingoteAlumínio",
    nome: "Lingote Alumínio",
    icon: "🧱",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },

  açoRefinado: {
    id: "açoRefinado",
    nome: "Aço Refinado",
    icon: "⬜",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },

  açoInox: {
    id: "açoInox",
    nome: "Aço Inox",
    icon: "💿",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },

  SeçãoCasco: {
    id: "SeçãoCasco",
    nome: "Seção Casco",
    icon: "🚢",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },

//aqui

  açoBalistico: {
    id: "açoBalistico",
    nome: "Aço Inox",
    icon: "⚙️",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },

  resíduosMetálicos: {
    id: "resíduosMetálicos",
    nome: "Resíduos Metálicos",
    icon: "⚙️",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },

  sucata: {
    id: "sucata",
    nome: "Sucata",
    icon: "🗑️",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },

  componenteConexão: {
    id: "componenteConexão",
    nome: "Componente Conexão",
    icon: "📡",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },

  módulo5G: {
    id: "módulo5G",
    nome: "Módulo 5G",
    icon: "📶",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },

  waferSilício: {
    id: "waferSilício",
    nome: "Wafer De Silício",
    icon: "💿",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  waferPotência: {
    id: "waferPotência",
    nome: "Wafer De Potência",
    icon: "💿",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  waferRF: {
    id: "waferRF",
    nome: "Wafer De RF",
    icon: "💠",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  célulaFuselagem: {
    id: "célulaFuselagem",
    nome: "Células De Fuselagem",
    icon: "🛡️",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  treliçaLeve: {
    id: "treliçaLeve",
    nome: "Treliça Leve",
    icon: "🪜",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  cockpit: {
    id: "cockpit",
    nome: "Cockpit",
    icon: "💺",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  amortecedor: {
    id: "amortecedor",
    nome: "Amortecedor",
    icon: "⛓️",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  silícioMetalúgico: {
    id: "silícioMetalúgico",
    nome: "Silício Metalúgico",
    icon: "❄️",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  silícioPuro: {
    id: "silícioPuro",
    nome: "Silício Puro",
    icon: "💎",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  unidadeAutomação: {
    id: "unidadeAutomação",
    nome: "Unidade De Automação",
    icon: "📟",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },
  nitrogênio: {
    id: "silícioPuro",
    nome: "Silício Puro",
    icon: "💨",
    unidade: "kg",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 6,
  },
  óleoBase: {
    id: "óleoBase",
    nome: "Óleo Base",
    icon: "🧴",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "químicos",
    slotSize: 6,
  },
  carbonoEletrônico: {
    id: "silícioPuro",
    nome: "Silício Puro",
    icon: "⚫",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },

  carbonetoSilício: {
    id: "carbonetoSilício",
    nome: "Carboneto De Silício",
    icon: "⚫",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 6,
  },

  calcário: {
    id: "calcário",
    nome: "Calcário",
    icon: "⛏️",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },

  arsênioBruto: {
    id: "arsênioBruto",
    nome: "Arsênio Bruto",
    icon: "⛏️",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },
//aqui
  arsênioPuro: {
    id: "arsênioPuro",
    nome: "Arsênio Puro",
    icon: "🧪",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },

  carvão: {
    id: "carvão",
    nome: "Carvão",
    icon: "⛏️",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },
  carvãoRefinado: {
    id: "carvãoRefinado",
    nome: "Carvão Refinado",
    icon: "⬛",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },
  grafiteIndustrial: {
    id: "grafiteIndustrial",
    nome: "Grafite Industrial",
    icon: "🔘",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },
  bauxita: {
    id: "bauxita",
    nome: "Bauxita",
    icon: "🧱",
    unidade: "tonelada",
    setor: "industria",
    categoriaFisica: "minério",
    slotSize: 6,
  },

  // 📱 TECNOLOGIA
  smartphoneBasico: {
    id: "smartphoneBasico",
    nome: "Smartphone Básico",
    icon: "📱",
    unidade: "unidade",
    setor: "tecnologia",
    categoriaFisica: "bens de alto valor",
    slotSize: 2,
  },
  smartphonePremium: {
    id: "smartphonePremium",
    nome: "Smartphone Premium",
    icon: "📱",
    unidade: "unidade",
    setor: "tecnologia",
    categoriaFisica: "bens de alto valor",
    slotSize: 2,
  },
  smartwatch: {
    id: "smartwatch",
    nome: "Smartwatch",
    icon: "⌚",
    unidade: "unidade",
    setor: "tecnologia",
    categoriaFisica: "bens de alto valor",
    slotSize: 2,
  },
  foneOuvido: {
    id: "foneOuvido",
    nome: "Fone De Ouvido",
    icon: "🎧",
    unidade: "unidade",
    setor: "tecnologia",
    categoriaFisica: "bens de alto valor",
    slotSize: 2,
  },
  computador: {
    id: "computador",
    nome: "Computador",
    icon: "💻",
    unidade: "unidade",
    setor: "tecnologia",
    categoriaFisica: "bens de alto valor",
    slotSize: 2,
  },
  consoleJogos: {
    id: "consoleJogos",
    nome: "Console De Jogos",
    icon: "🎮",
    unidade: "unidade",
    setor: "tecnologia",
    categoriaFisica: "bens de alto valor",
    slotSize: 2,
  },
  unidadeServidor: {
    id: "unidadeServidor",
    nome: "Unidade De Servidor",
    icon: "🗄️",
    unidade: "unidade",
    setor: "tecnologia",
    categoriaFisica: "bens de alto valor",
    slotSize: 2,
  },


  // ⚡ ENERGIA
  bateriaUsada: {
    id: "bateriaUsada",
    nome: "Bateria Usada",
    icon: "🪫",
    unidade: "unidade",
    setor: "energia",
    categoriaFisica: "componentes industriais",
    slotSize: 200,
  },

  painelSolar: {
    id: "painelSolar",
    nome: "Painel Solar",
    icon: "☀️",
    unidade: "unidade",
    setor: "energia",
    categoriaFisica: "componentes industriais",
    slotSize: 200,
  },

  minerioUranio: {
    id: "minerioUranio",
    nome: "minerioUranio",
    icon: "☢️",
    unidade: "unidade",
    setor: "energia",
    categoriaFisica: "materiais sensíveis",
    slotSize: 200,
  },

  combustivelCarro: {
    id: "combustivelCarro",
    nome: "combustivelCarro",
    icon: "⛽",
    unidade: "L",
    setor: "comercio",
    categoriaFisica: "fluidos",
    slotSize: 3,
  },

  processadorSimples: {
    id: "processadorSimples",
    nome: "Processador Simples",
    icon: "📟",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes eletrônicos",
    slotSize: 3,
  },

  placaMãe: {
    id: "placaMãe",
    nome: "Placa Mãe",
    icon: "🟩",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes eletrônicos",
    slotSize: 3,
  },

  tela: {
    id: "tela",
    nome: "Tela",
    icon: "📺",
    unidade: "unidade",
    setor: "industria",
    categoriaFisica: "componentes eletrônicos",
    slotSize: 3,
  },

  portaCarro: {
    id: "portaCarro",
    nome: "portaCarro",
    icon: "🔘",
    unidade: "kg",
    setor: "industria",
    categoriaFisica: "componentes industriais",
    slotSize: 10,
  },
  turbinaEólica: {
    id: "turbinaEólica",
    nome: "Turbina Eólica",
    icon: "🌬️",
    unidade: "kg",
    setor: "energia",
    categoriaFisica: "componentes industriais",
    slotSize: 10,
  },
//aqui
  softwareSimples: {
    id: "softwareSimples",
    nome: "softwareSimples",
    icon: "💾",
    unidade: "gb",
    setor: "tecnologia",
    categoriaFisica: "produtos digitais",
    slotSize: 100,
  },
  relogioLuxo: {
    id: "relogioLuxo",
    nome: "relogioLuxo",
    icon: "⌚",
    unidade: "gb",
    setor: "comercio",
    categoriaFisica: "bens de alto valor",
    slotSize: 5,
  },
  // energiaLimpa: {
  //   id: "energiaLimpa",
  //   nome: "Energia Limpa",
  //   icon: "⚡",
  //   unidade: "MWh",
  //   setor: "energia",
  //   categoriaFisica: "energia",
  //   slotSize: 1,
  // },
  // energiaComum: {
  //   id: "energiaLimpa",
  //   nome: "Energia Limpa",
  //   icon: "⚡",
  //   unidade: "MWh",
  //   setor: "energia",
  //   categoriaFisica: "energia",
  //   slotSize: 1,
  // },
  // energiaNuclear: {
  //   id: "energiaLimpa",
  //   nome: "Energia Limpa",
  //   icon: "⚡",
  //   unidade: "MWh",
  //   setor: "energia",
  //   categoriaFisica: "energia",
  //   slotSize: 1,
  // },
};


/* =====================================================
   💰 PREÇOS BASE DO MERCADO (SEM ESTOQUE)
===================================================== */

export const marketPrices = {
  sementeMilho: 100,
  sementeSoja: 100,
  sementeTrigo: 100,
  sementeAlgodão: 100,
  milho: 250,
  soja: 250,
  trigo: 250,
  algodão: 250,
  ervaAnalgésica: 450,
  plantaAntissépticas: 450,
  vaca: 1200,
  galinha: 300,
  ovelha: 1200,
  porco: 1200,
  couro: 400,
  couroPremium: 1500,
  lã: 400,
  arvoreEucalipto: 600,
  arvoreNativa: 600,
  toraEucalipto: 1500,
  toraNativa: 1500,
  sodaCáustica: 5500,
  ácidoSulfúrico: 5500,
  sal: 3000,
  benzeno: 3000,
  enxofreBruto: 3000,
  cloro: 3000,
  pigmento: 2500,
  cavacoMadeiraNativa: 800,
  cavacoEucalipto: 800,
  fardoCelulose: 4200,
  bobinaKraft: 7000,
  bobinaBranco: 7000,
  tintaIndustrial: 400,
  livroComum: 150,
  livroPremium: 600,
  fioAlgodão: 1200,
  fioLã: 2800,
  fioIndustrial: 2800,
  colaIndustrial: 2500,
  petróleoBruto: 400,
  diesel: 8000,
  solvente: 8000,
  nafta: 8000,
  caixaPapelão: 250,
  caixaPequenaPapelão: 250,
  sacolaPapelão: 300,
  sacasIndustriais: 300,
  tecidoTecnico: 4500,
  aditivoDeNylon: 4500,
  saisDeCromo: 5000,
  polímero: 5000,
  vidroTécnico: 6500,
  pvcIndustrial: 6500,
  resinaEmbalagem: 7000,
  termoplásticoRígido: 12000,
  plásticoIsolante: 12000,
  óleoAntimicrobiano: 15000,
  óleoIndustrial: 15000,
  extratoAlívio: 18000,
  pASintético: 18000,
  resinaIndustrial: 7000,
  excipienteFarmacêutico: 22000,
  comprimidosGenéricos: 150,
  frascoVitamina: 350,
  bisnagaTratamento: 350,
  testeLaboratorial: 45000,
  enzimaIndustrial: 45000,
  polímeroReforçado: 25000,
  camisetaAlgodão: 80,
  casacoLã: 350,
  roupasDryFit: 350,
  tenisCorrida: 800,
  sapatoLuxo: 800,
  biomassaLíquida: 4000,
  serragem: 50,
  esterco: 50,
  racaoDeVacas: 180,
  racaoDeAves: 180,
  racaoDeOvinos: 180,
  racaoDePorco: 180,
  fertilizantePlantação: 2000,
  fertilizanteFlorestal: 2000,
  carneBovina: 250,
  frango: 120,
  carneSuina: 200,
  carneOvino: 180,
  carroPopular: 90000,
  carroEsportivo: 450000,
  carroElétrico: 1200000,
  hiperCarroElétrico: 6000000,
  caminhãoElétrico: 1200000,
  escavadeira: 2500000,
  suv: 450000,
  van: 450000,
  minérioFerro: 1200,
  minérioDeCobre: 1200,
  minérioDeChumbo: 1200,
  lingoteChumbo: 5000,
  lingoteDeCobre: 5000,
  minérioDeEstanho: 3500,
  minérioDeZinco: 3500,
  minérioDeGalho: 22000,
  minérioDeIndio: 22000,
  minérioDeNiquel: 15000,
  minérioDeCobalto: 15000,
  minérioDeQuartzo: 8000,
  minérioDePrata: 15000,
  minérioDeOuro: 15000,
  minérioDeLítio: 25000,
  lítioPuro: 80000,
  nanotuboCarbono: 80000,
  sondaTerreno: 750000,
  scannerMédico: 750000,
  chipIA: 85000,
  chipWearables: 85000,
  computadorVoo: 1200000,
  processadorBlindado: 150000,
  processadorSísmico: 2500000,
  sistemaGuia: 350000,
  bioChip: 1800000,
  câmeraPrecisão: 150000,
  sensoresCampoRemoto: 280000,
  lentePrecisão: 32000,
  unidadeComando: 350000,
  chipMemória: 12000,
  controle: 1200,
  painélDeControle: 45000,
  minérioDeManganês: 3500,
  minérioDeCromo: 18000,
  minérioNeodímio: 25000,
  minérioDeTitânio: 25000,
  ligaDeBronze: 8500,
  ligaDeSolda: 8500,
  ligaDeLatão: 8500,
  superligaTérmica: 45000,
  ligaDeOuro: 45000,
  compostoSemicondutor: 65000,
  celulaSolar: 65000,
  engrenagem: 8500,
  placaIndustrial: 150000,
  robôServiço: 1500000,
  controladorLógico: 95000,
  ControladorCarga: 25000,
  placaGestãoEnergia: 95000,
  placaFrequência: 110000,
  processadorAltaPerformance: 150000,
  bateriaPortátil: 18000,
  microControlador: 12000,
  droneLogístico: 90000,
  robôMineração: 850000,
  palhetaPrecisão: 35000,
  rolamento: 8500,
  fioCobre: 8500,
  microMotor: 12000,
  motorCombustão: 45000,
  motorElétrico: 45000,
  motorAvião: 8500000,
  motorFoguete: 8500000,
  motorNaval: 8500000,
  motorMíssil: 15000000,
  jatoComercial: 150000000,
  aviãoCargueiro: 180000000,
  caçaDefesa: 250000000,
  satéliteOrbital: 400000000,
  sondaEspacial: 850000000,
  fogueteLançamento: 450000000,
  navioConteineres: 120000000,
  navioPetroleiro: 150000000,
  navioPesquisa: 220000000,
  unidadeCélula: 8000,
  bateriaTracionamento: 95000,
  armazenamentoFixo: 150000,
  pistãoHidráulico: 1500,
  braçoHidráulico: 650000,
  TurbinaEstacionária: 400,
  blocoMagnético: 25000,
  contatoDePrata: 12000,
  periférico: 400,
  ferroGusa: 400,
  lingoteAço: 400,
  chapaAço: 400,
  chassiStandard: 15000,
  chassiLuxo: 45000,
  vigaH: 12000,
  chapaAlumínio: 400,
  chapaAltaTensão: 55000,
  placaReforçada: 400,
  sistemaTransmissão: 400,
  válvulaHidráulica: 21000,
  redutorCarga: 400,
  lingoteTitânio: 18000,
  lingoteAlumínio: 3500,
  açoRefinado: 18000,
  açoInox: 22000,
  SeçãoCasco: 450000,
  componenteConexão: 12500,
  açoBalistico: 95000,
  sucata: 400,
  módulo5G: 110000,
  waferSilício: 90000,
  waferPotência: 8500,
  waferRF: 85000,
  célulaFuselagem: 1200000,
  treliçaLeve: 400,
  cockpit: 25000,
  amortecedor: 5500,
  silícioMetalúgico: 400,
  silícioPuro: 400,
  unidadeAutomação: 250000,
  nitrogênio: 400,
  óleoBase: 1500,
  carbonoEletrônico: 5000,
  carbonetoSilício: 400,
  calcário: 400,
  arsênioBruto: 400,
  arsênioPuro: 28000,
  carvão: 400,
  carvãoRefinado: 400,
  grafiteIndustrial: 400,
  bauxita: 1200,
  smartphoneBasico: 2000,
  smartphonePremium: 7500,
  smartwatch: 2800,
  foneOuvido: 1200,
  computador: 5000,
  consoleJogos: 4500,
  unidadeServidor: 2500000,
  bateriaUsada: 1500,
  painelSolar: 4500,
  minerioUranio: 400,
  processadorSimples: 400,
  placaMãe: 350000,
  tela: 400,
  portaCarro: 400,
  turbinaEólica: 650000,
  softwareSimples: 400,
  relogioLuxo: 400,
  // energiaLimpa: 450,
  // energiaComum: 250,
  // energiaNuclear: 180,
};



/* =====================================================
   ⚖️ FUNÇÃO PURA DE MULTIPLICADOR ECONÔMICO
===================================================== */

function getEconomyMultiplier(estado) {
  switch (estado) {
    case "recessão":
      return 0.8;
    case "declínio":
      return 0.9;
    case "estável":
      return 1;
    case "progressiva":
      return 1.1;
    case "aquecida":
      return 1.2;
    default:
      return 1;
  }
}

/* =====================================================
   🧮 FUNÇÃO PURA DE PREÇO DE MERCADO
===================================================== */

export function getMarketPrice(produtoId, economiaSetores) {
  const basePrice = marketPrices[produtoId];
  if (!basePrice) return 0;

  const produto = productsCatalog[produtoId];
  if (!produto) return 0;

  const setor = produto.setor;

  const economiaGlobalEstado =
    economiaSetores.economiaGlobal ?? "estável";

  const economiaSetorEstado =
    economiaSetores[setor]?.economiaSetor?.estadoAtual ?? "estável";

  const globalMultiplier = getEconomyMultiplier(economiaGlobalEstado);
  const sectorMultiplier = getEconomyMultiplier(economiaSetorEstado);

  return Math.round(basePrice * globalMultiplier * sectorMultiplier);
}
/* =====================================================
   🏪 COMPONENTE DE VENDA DE PRODUTO
===================================================== */

function VendaProduto({ nome, icon, preco, unidade }) {
  return (
    <div className="flex justify-between items-center p-3 border rounded">
      <div className="flex items-center gap-2">
        <span>{icon}</span>
        <strong>{nome}</strong>
      </div>
      <span>
        R$ {preco} / {unidade}
      </span>
    </div>
  );
}

/* =====================================================
   🧾 MERCADO GLOBAL (interface única)
===================================================== */

export function MercadoGlobal() {
  const { economiaSetores } = useContext(DadosEconomyGlobalContext);

  return (
    <div className="space-y-3">
      <h2 className="text-xl font-bold">🌍 Mercado Global</h2>

      {Object.keys(productsCatalog).map((id) => {
        const produto = productsCatalog[id];
        const preco = getMarketPrice(id, economiaSetores);

        return (
          <VendaProduto
            key={id}
            nome={produto.nome}
            icon={produto.icon}
            preco={preco}
            unidade={produto.unidade}
          />
        );
      })}
    </div>
  );
}


/* =====================================================
   🚀 USO FINAL
===================================================== */

// Envolver o app:
// <DadosEconomyProvider>
//    <MercadoGlobal />
// </DadosEconomyProvider>